export const agentExecutorAbi = [
  {
    type: "function",
    name: "createPolicy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agent", type: "address" },
      { name: "tokenIn", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "maxAmount", type: "uint256" },
      { name: "maxSlippageBps", type: "uint256" },
      { name: "minOpportunityScore", type: "uint256" },
      { name: "cooldown", type: "uint256" },
      { name: "expiry", type: "uint256" },
    ],
    outputs: [{ name: "policyId", type: "uint256" }],
  },
  {
    type: "function",
    name: "policies",
    stateMutability: "view",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "agent", type: "address" },
      { name: "tokenIn", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "maxAmount", type: "uint256" },
      { name: "maxSlippageBps", type: "uint256" },
      { name: "minOpportunityScore", type: "uint256" },
      { name: "cooldown", type: "uint256" },
      { name: "lastExecution", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "getOwnerPolicyIds",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "isPolicyExecutable",
    stateMutability: "view",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "executeDecision",
    stateMutability: "nonpayable",
    inputs: [
      { name: "policyId", type: "uint256" },
      {
        name: "decision",
        type: "tuple",
        components: [
          { name: "decisionId", type: "bytes32" },
          { name: "tokenIn", type: "address" },
          { name: "tokenOut", type: "address" },
          { name: "amountIn", type: "uint256" },
          { name: "amountOutMin", type: "uint256" },
          { name: "opportunityScore", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "evidenceHash", type: "bytes32" },
        ],
      },
    ],
    outputs: [{ name: "amounts", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "commitDecision",
    stateMutability: "nonpayable",
    inputs: [
      { name: "policyId", type: "uint256" },
      { name: "decisionId", type: "bytes32" },
      { name: "evidenceHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "PolicyCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "policyId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: true, name: "agent", type: "address" },
      { indexed: false, name: "tokenIn", type: "address" },
      { indexed: false, name: "tokenOut", type: "address" },
      { indexed: false, name: "maxAmount", type: "uint256" },
      { indexed: false, name: "maxSlippageBps", type: "uint256" },
      { indexed: false, name: "minOpportunityScore", type: "uint256" },
      { indexed: false, name: "cooldown", type: "uint256" },
      { indexed: false, name: "expiry", type: "uint256" },
    ],
  },
] as const;
